BUWebApp/Areas/Accounting/Controllers/AccountInvoiceController.cs
using BusinessLayer;
using BusinessLayer.Helper;
using BusinessLayer.Model;
using BUWebApp.Areas.Supervisor.Models;
using DomainModel;
using Microsoft.Reporting.WebForms;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BUWebApp.Areas.Accounting.Controllers
{
    [Authorize(Roles = "Accounting")]
    public class AccountInvoiceController : Controller
    {
        [HttpGet]
        public ActionResult Search(string accountInvoiceNo)
        {
            ViewBag.AccountInvoiceNo = accountInvoiceNo;
            if (string.IsNullOrEmpty(accountInvoiceNo))
            {
                ViewBag.AccountInvoices = new List<AccountInvoice>();
                return View();
            }
            ViewBag.AccountInvoices = BuyingFacade.AccountInvoiceBL()
                .SearchByInvoiceNo(accountInvoiceNo);
            return View();
        }

        [HttpGet]
        public ActionResult Details(string accountInvoiceNo)
        {
            var accountInvoice = BuyingFacade.AccountInvoiceBL().GetSingle(accountInvoiceNo);
            var invoice = BuyingFacade.InvoiceBL().GetSingle(accountInvoice.RefInvoiceNo);

            ViewBag.AccountInvoice = accountInvoice;
            ViewBag.Invoice = invoice;
            ViewBag.AccountInvoiceDetails = InvoiceDetailsHelper
                .GetByAccountInvoiceNo(accountInvoiceNo);
            ViewBag.Registration = BuyingFacade.RegistrationBL()
                .GetSingle(invoice.Crop, invoice.FarmerCode);
            return View();
        }

        [HttpGet]
        public ActionResult Print(string accountInvoiceNo)
        {
            var accountInvoice = BuyingFacade.AccountInvoiceBL()
                .GetSingle(accountInvoiceNo);
            if (accountInvoice.IsPrinted == true)
                throw new Exception("Invoice No. " + accountInvoiceNo +
                    " นี้ถูกพิมพ์ไปแล้วเมื่อ " + accountInvoice.PrintDate +
                    " โดย " + accountInvoice.PrintBy +
                    " หากต้องการพิมพ์ใบเสร็จใหม่ โปรดติดต่อไปยังแผนกบัญชีเพื่อทำการปลดล็อคให้พิมพ์ใหม่");

            var invoiceDetails = BusinessLayer.Helper.InvoiceDetailsHelper.GetByAccountInvoiceNo(accountInvoiceNo);
            if (accountInvoice == null)
                throw new Exception("ไม่พบข้อมูล invoice นี้ในระบบ");

            if (accountInvoice.Invoice == null)
                throw new Exception("ไม่พบข้อมูล invoice นี้ในระบบ");

            ReportDataSource farmerProfileDataSource = new ReportDataSource();
            ReportDataSource cropInputsDetailsDataSource = new ReportDataSource();
            ReportDataSource currencyToThaiBathDataSource = new ReportDataSource();

            BuyingSystemDataSet.FarmerProfileDataTable farmerProfileDataTable = new BuyingSystemDataSet.FarmerProfileDataTable();
            BuyingSystemDataSet.sp_CropInputsInvoiceDetailsDataTable sp_CropInputsInvoiceDetailsDataTable = new BuyingSystemDataSet.sp_CropInputsInvoiceDetailsDataTable();
            BuyingSystemDataSet.CurrencyToThaiBathDataTable currencyToThaiBathDataTable = new BuyingSystemDataSet.CurrencyToThaiBathDataTable();

            BUWebApp.BuyingSystemDataSetTableAdapters.FarmerProfileTableAdapter farmerProfileTableAdapter = new BuyingSystemDataSetTableAdapters.FarmerProfileTableAdapter();
            BUWebApp.BuyingSystemDataSetTableAdapters.sp_CropInputsInvoiceDetailsTableAdapter sp_CropInputsInvoiceDetailsTableAdapter = new BuyingSystemDataSetTableAdapters.sp_CropInputsInvoiceDetailsTableAdapter();
            BUWebApp.BuyingSystemDataSetTableAdapters.CurrencyToThaiBathTableAdapter currencyToThaiBathTableAdapter = new BuyingSystemDataSetTableAdapters.CurrencyToThaiBathTableAdapter();

            farmerProfileTableAdapter.Fill(farmerProfileDataTable, accountInvoice.Invoice.Crop, accountInvoice.Invoice.FarmerCode);
            sp_CropInputsInvoiceDetailsTableAdapter.Fill(sp_CropInputsInvoiceDetailsDataTable, accountInvoiceNo);

            var currency = invoiceDetails.Sum(x => x.UnitPrice * x.Quantity);
            currencyToThaiBathTableAdapter.Fill(currencyToThaiBathDataTable, accountInvoiceNo);

            farmerProfileDataSource.Name = "FarmerProfile";
            farmerProfileDataSource.Value = farmerProfileDataTable;

            cropInputsDetailsDataSource.Name = "CropInputsInvoiceDetails";
            cropInputsDetailsDataSource.Value = sp_CropInputsInvoiceDetailsDataTable;

            currencyToThaiBathDataSource.Name = "CurrencyToThaiBath";
            currencyToThaiBathDataSource.Value = currencyToThaiBathDataTable;

            var farmer = BuyingFacade.FarmerBL().GetByFarmerCode(accountInvoice.Invoice.FarmerCode);
            string area = area = farmer.Supplier1.SupplierArea;
            string reportPath = "";

            if (area == "SUK" && accountInvoiceNo.Substring(1, 2) == "IV")
            {
                reportPath = Server.MapPath("~/RDLC/PIV-1.rdlc");
            }
            else
            {
                switch (accountInvoiceNo.Substring(1, 2))
                {
                    case "ON":
                        reportPath = Server.MapPath("~/RDLC/PON.rdlc");
                        break;
                    case "IN":
                        reportPath = Server.MapPath("~/RDLC/PIN.rdlc");
                        break;
                    case "OV":
                        reportPath = Server.MapPath("~/RDLC/POV.rdlc");
                        break;
                    case "IV":
                        reportPath = Server.MapPath("~/RDLC/PIV.rdlc");
                        break;
                    default:
                        break;
                }
            }

            LocalReport report = new LocalReport();

            report.DataSources.Add(farmerProfileDataSource);
            report.DataSources.Add(cropInputsDetailsDataSource);
            report.DataSources.Add(currencyToThaiBathDataSource);
            report.ReportPath = reportPath;

            string filePath = Path.GetTempFileName();
            Export(report, filePath);

            //Clost Report object.           
            report.Dispose();
            BuyingFacade.AccountInvoiceBL()
                .LockPrint(accountInvoice.InvoiceNo, HttpContext.User.Identity.Name);

            return File(filePath, "application/pdf");
        }

        public string Export(LocalReport report, string filePath)
        {
            string ack = "";
            try
            {
                Warning[] warnings;
                string[] streamids;
                string mimeType;
                string encoding;
                string extension;

                byte[] bytes = report.Render("PDF", null, out mimeType, out encoding, out extension, out streamids, out warnings);
                using (FileStream stream = System.IO.File.OpenWrite(filePath))
                {
                    stream.Write(bytes, 0, bytes.Length);
                }
                return ack;
            }
            catch (Exception ex)
            {
                ack = ex.InnerException.Message;
                return ack;
            }
        }

        [HttpGet]
        public ActionResult UnlockPrint(string accountInvoiceNo)
        {
            BuyingFacade.AccountInvoiceBL().UnLockPrint(accountInvoiceNo);
            return RedirectToAction("Details", new { accountInvoiceNo = accountInvoiceNo });
        }
    }
}

BUWebApp/Areas/Supervisor/Controllers/AccountInvoiceController.cs
using BusinessLayer;
using BusinessLayer.Helper;
using BUWebApp.Areas.Supervisor.Models;
using Microsoft.Reporting.WebForms;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BUWebApp.Areas.Supervisor.Controllers
{
    [Authorize(Roles = "Supervisor")]
    public class AccountInvoiceController : Controller
    {
        [HttpGet]
        public ActionResult Index(string refInvoiceNo)
        {
            var invoice = BuyingFacade.InvoiceBL().GetSingle(refInvoiceNo);
            ViewBag.Farmer = BuyingFacade.FarmerBL().GetByFarmerCode(invoice.FarmerCode);
            return View(BuyingFacade.AccountInvoiceBL().GetByRefInvoice(refInvoiceNo));
        }

        [HttpGet]
        public ActionResult Details2(string accountInvoiceNo)
        {
            var accountInvoice = BuyingFacade.AccountInvoiceBL().GetSingle(accountInvoiceNo);
            if (accountInvoice == null)
                throw new Exception("ไม่พบ ใบเสร็จ/ใบส่งของ(account invoice no) นี้ในระบบ");

            ViewBag.Farmer = BuyingFacade.FarmerBL()
                .GetByFarmerCode(accountInvoice.Invoice.FarmerCode);
            ViewBag.InvoiceDetailList = InvoiceDetailsHelper
                .GetByAccountInvoiceNo(accountInvoiceNo);
            ViewBag.AccountInvoice = accountInvoice;

            return View();
        }

        [HttpGet]
        public ActionResult Details(string accountInvoiceNo)
        {
            var accountInvoice = BuyingFacade.AccountInvoiceBL().GetSingle(accountInvoiceNo);
            var invoice = BuyingFacade.InvoiceBL().GetSingle(accountInvoice.RefInvoiceNo);

            ViewBag.CreditNoteList = BuyingFacade.AccountCreditNoteBL().GetByAccountInvoice(accountInvoiceNo);
            ViewBag.InvoiceDetailList = InvoiceDetailsHelper.GetByAccountInvoiceNo(accountInvoiceNo);
            ViewBag.AccountInvoice = accountInvoice;
            ViewBag.Invoice = invoice;

            var model = new vm_CreditNote();

            model.AccountInvoice = accountInvoice;
            model.AccountInvoiceNo = accountInvoiceNo;
            model.CreateDate = DateTime.Now;
            model.CreditNoteList = BuyingFacade.AccountCreditNoteBL().GetByAccountInvoice(accountInvoiceNo);
            model.Farmer = BuyingFacade.FarmerBL().GetByFarmerCode(accountInvoice.Invoice.FarmerCode);

            return View(model);
        }

        [HttpGet]
        public ActionResult Print(string accountInvoiceNo)
        {
            var accountInvoice = BuyingFacade.AccountInvoiceBL()
                .GetSingle(accountInvoiceNo);
            if (accountInvoice.IsPrinted == true)
                throw new Exception("Invoice No. " + accountInvoiceNo +
                    " นี้ถูกพิมพ์ไปแล้วเมื่อ " + accountInvoice.PrintDate +
                    " โดย " + accountInvoice.PrintBy +
                    " หากต้องการพิมพ์ใบเสร็จใหม่ โปรดติดต่อไปยังแผนกบัญชีเพื่อทำการปลดล็อคให้พิมพ์ใหม่");

            var invoiceDetails = InvoiceDetailsHelper.GetByAccountInvoiceNo(accountInvoiceNo);
            if (accountInvoice == null)
                throw new Exception("ไม่พบข้อมูล invoice นี้ในระบบ");

            if (accountInvoice.Invoice == null)
                throw new Exception("ไม่พบข้อมูล invoice นี้ในระบบ");

            ReportDataSource farmerProfileDataSource = new ReportDataSource();
            ReportDataSource cropInputsDetailsDataSource = new ReportDataSource();
            ReportDataSource currencyToThaiBathDataSource = new ReportDataSource();

            BuyingSystemDataSet.FarmerProfileDataTable farmerProfileDataTable = new BuyingSystemDataSet.FarmerProfileDataTable();
            BuyingSystemDataSet.sp_CropInputsInvoiceDetailsDataTable sp_CropInputsInvoiceDetailsDataTable = new BuyingSystemDataSet.sp_CropInputsInvoiceDetailsDataTable();
            BuyingSystemDataSet.CurrencyToThaiBathDataTable currencyToThaiBathDataTable = new BuyingSystemDataSet.CurrencyToThaiBathDataTable();

            BuyingSystemDataSetTableAdapters.FarmerProfileTableAdapter farmerProfileTableAdapter = new BuyingSystemDataSetTableAdapters.FarmerProfileTableAdapter();
            BuyingSystemDataSetTableAdapters.sp_CropInputsInvoiceDetailsTableAdapter sp_CropInputsInvoiceDetailsTableAdapter = new BuyingSystemDataSetTableAdapters.sp_CropInputsInvoiceDetailsTableAdapter();
            BuyingSystemDataSetTableAdapters.CurrencyToThaiBathTableAdapter currencyToThaiBathTableAdapter = new BuyingSystemDataSetTableAdapters.CurrencyToThaiBathTableAdapter();

            farmerProfileTableAdapter.Fill(farmerProfileDataTable, accountInvoice.Invoice.Crop, accountInvoice.Invoice.FarmerCode);
            sp_CropInputsInvoiceDetailsTableAdapter.Fill(sp_CropInputsInvoiceDetailsDataTable, accountInvoiceNo);

            var currency = invoiceDetails.Sum(x => x.UnitPrice * x.Quantity);
            currencyToThaiBathTableAdapter.Fill(currencyToThaiBathDataTable, accountInvoiceNo);

            farmerProfileDataSource.Name = "FarmerProfile";
            farmerProfileDataSource.Value = farmerProfileDataTable;

            cropInputsDetailsDataSource.Name = "CropInputsInvoiceDetails";
            cropInputsDetailsDataSource.Value = sp_CropInputsInvoiceDetailsDataTable;

            currencyToThaiBathDataSource.Name = "CurrencyToThaiBath";
            currencyToThaiBathDataSource.Value = currencyToThaiBathDataTable;

            var farmer = BuyingFacade.FarmerBL().GetByFarmerCode(accountInvoice.Invoice.FarmerCode);
            string area = area = farmer.Supplier1.SupplierArea;
            string reportPath = "";

            if (area == "SUK" && accountInvoiceNo.Substring(1, 2) == "IV")
            {
                reportPath = Server.MapPath("~/RDLC/PIV-1.rdlc");
            }
            else
            {
                switch (accountInvoiceNo.Substring(1, 2))
                {
                    case "ON":
                        reportPath = Server.MapPath("~/RDLC/PON.rdlc");
                        break;
                    case "IN":
                        reportPath = Server.MapPath("~/RDLC/PIN.rdlc");
                        break;
                    case "OV":
                        reportPath = Server.MapPath("~/RDLC/POV.rdlc");
                        break;
                    case "IV":
                        reportPath = Server.MapPath("~/RDLC/PIV.rdlc");
                        break;
                    default:
                        break;
                }
            }

            LocalReport report = new LocalReport();

            report.DataSources.Add(farmerProfileDataSource);
            report.DataSources.Add(cropInputsDetailsDataSource);
            report.DataSources.Add(currencyToThaiBathDataSource);
            report.ReportPath = reportPath;

            string filePath = Path.GetTempFileName();
            //throw new Exception(filePath);

            Export(report, filePath);

            //Clost Report object.           
            report.Dispose();
            BuyingFacade.AccountInvoiceBL()
                .LockPrint(accountInvoice.InvoiceNo, HttpContext.User.Identity.Name);

            return File(filePath, "application/pdf");
        }

        public string Export(LocalReport report, string filePath)
        {
            string ack = "";
            try
            {
                Warning[] warnings;
                string[] streamids;
                string mimeType;
                string encoding;
                string extension;

                byte[] bytes = report.Render("PDF", null, out mimeType, out encoding, out extension, out streamids, out warnings);
                using (FileStream stream = System.IO.File.OpenWrite(filePath))
                {
                    stream.Write(bytes, 0, bytes.Length);
                }
                return ack;
            }
            catch (Exception ex)
            {
                ack = ex.InnerException.Message;
                return ack;
            }
        }
    }
}

BUWebApp/Areas/Supervisor/Views/AccountInvoice/Details.cshtml
@model BUWebApp.Areas.Supervisor.Models.vm_CreditNote

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Supervisor/Views/Shared/_Layout.cshtml";
    var invoice = (DomainModel.Invoice)ViewBag.Invoice;
    var accountInvoice = (DomainModel.AccountInvoice)ViewBag.AccountInvoice;
    var creditNoteList = (List<DomainModel.AccountCreditNote>)ViewBag.CreditNoteList;
    var invoiceDetailList = (List<BusinessLayer.Model.m_InvoiceDetails>)ViewBag.InvoiceDetailList;
    var returnController = Model.AccountInvoiceNo.Contains("N") ? "InvoiceExcludeVat" : "InvoiceIncludeVat";
}

<script type="text/javascript">
    $(document).ready(function () {
        $("#confirmSubmitButton").click(function (e) {
            if (fromValidation() == false) {
                e.preventDefault();
            }
        });
    });

    function fromValidation() {
        if ($("#CreateDate").val() == null || $("#CreateDate").val() == "") {
            alert("โปรดระบุวันที่สร้างเอกสารใบลดหนี้");
            $("#CreateDate").focus();
            return false;
        }

        if ($("#Description").val() == null || $("#Description").val() == "") {
            alert("โปรดระบุหมายเหตุของการทำใบลดหนี้");
            $("#Description").focus();
            return false;
        }

        if ($("#IsPayForCash").is(":checked") == true) {
            var result = confirm("ท่านต้องการออกใบลดหนี้แบบชำระเป็นเงินสดใช่หรือไม่?");
            if (result == false)
                return false;
        }

        return true;
    }
</script>

<h3>Account Invoice Details</h3>
<h6>รายละเอียดข้อมูลการจ่ายปัจจัยการผลิต</h6>
<hr />

<table class="table table-bordered table-striped">
    <tr>
        <th colspan="2">รายละเอียดใบส่งปัจจัยการผลิต</th>
    </tr>
    <tr>
        <td>Account Invoice #</td>
        <td>@accountInvoice.InvoiceNo</td>
    </tr>
    <tr>
        <td>Ref. Invoice #</td>
        <td>@accountInvoice.RefInvoiceNo</td>
    </tr>
    <tr>
        <td>Farmer Name</td>
        <td>@Model.Farmer.Person.Prefix@Model.Farmer.Person.FirstName  @Model.Farmer.Person.LastName </td>
    </tr>
    <tr>
        <td>Total Price</td>
        <td>@invoiceDetailList.Sum(x => x.UnitPrice * x.Quantity).ToString("N0") ฿</td>
    </tr>
    <tr>
        <td>Print Status</td>
        <td>
            @if (accountInvoice.IsPrinted)
            {
                <span style="color:green;">พิมพ์เอกสารออกจากระบบแล้ว</span>
            }
            else
            {
                <span style="color:red;">**ยังไม่ได้พิมพ์เอกสารออกจากระบบ</span>
            }
        </td>
    </tr>
    <tr>
        <td>Print Date</td>
        <td>@accountInvoice.PrintDate</td>
    </tr>
</table>

<table id="invoiceDetailsTable" class="table table-striped table-bordered">
    <thead class="table-dark">
        <tr class="table-success">
            <th>ชำระเงินสด</th>
            <th>ประเภท</th>
            <th>รายละเอียด</th>
            <th>ยี่ห้อ</th>
            <th>หน่วยนับ</th>
            <th>แพ็คเกจ</th>
            @*<th>deduction</th>*@
            <th>จำนวน</th>
            <th>ราคาต่อหน่วย</th>
            <th>ราคา</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in invoiceDetailList.OrderBy(x => x.Category).ThenBy(x => x.ItemName))
        {
            var price = (item.UnitPrice * item.Quantity).ToString("N2");
            <tr>
                <td style="text-align:center;">
                    @if (item.IsCash == true)
                    {
                        <input type="checkbox" name="isCashes" value="@item.ConditionID" checked="checked" />
                    }
                    else
                    {
                        <input type="checkbox" name="isCashes" value="@item.ConditionID" />
                    }
                </td>
                <td>
                    @item.Category
                </td>
                <td>
                    @item.ItemName
                </td>
                <td>
                    @item.Brand
                </td>
                <td>
                    @item.Unit
                </td>
                <td style="text-align:center;">
                    @if (item.PackageCode != null)
                    {
                        <i title="@item.PackageCode" class="fa fa-check-circle" style="color:green;"></i>
                    }
                </td>
                @*<td style="text-align:center;">
                        @if (item.CropInputsCondition.IsDeduction == true)
                        {
                            <i title="หักเงินจากการขาย" class="fa fa-check-circle" style="color:green;"></i>
                        }
                    </td>*@
                <td style="text-align:right;">
                    @item.Quantity.ToString("N0")
                </td>
                <td style="text-align:right;">
                    @item.UnitPrice.ToString("N2")
                </td>
                <td style="text-align:right;">
                    @price
                </td>
            </tr>
        }
    </tbody>
</table>

<div style="margin-bottom:20px;">
    @if (Model.AccountInvoice.IsPrinted == false)
    {
        <a href="@Url.Action("Print", "AccountInvoice", new { accountInvoiceNo = accountInvoice.InvoiceNo })" class="btn btn-primary" target="_blank"><i class="fa fa-print"></i> พิมพ์ใบส่งปัจจัยการผลิต</a>
    }
    <button class="btn btn-success" data-toggle="modal" data-target="#createModal"><i class="fa fa-pencil-square-o"></i> ออกใบลดหนี้/ใบเสร็จ</button>
    <a href="@Url.Action("Index", returnController, new { farmerCode = invoice.FarmerCode })" class="btn btn-outline-secondary">ย้อนกลับ</a>
</div>

@if (creditNoteList.Count() <= 0)
{
    <div class="alert alert-danger">
        ใบส่งปัจจัยการผลิตนี้ ยังไม่มีการบันทึกข้อมูลใบลดหนี้ในระบบ
    </div>
}
else
{
    <div class="row" style="margin-top:20px;">
        <div class="col-sm-12">
            <table class="table table-hover table-striped">
                <thead class="table-success">
                    <tr>
                        <th>
                            รหัสใบลดหนี้
                        </th>
                        <th>
                            ใบลดหนี้/ใบเสร็จ
                        </th>
                        <th>
                            ชำระเป็นเงินสด
                        </th>
                        <th>
                            รายละเอียด / หมายเหตุ
                        </th>
                        <th>
                            วันที่เอกสาร
                        </th>
                        <th>
                            บันทึกโดย
                        </th>
                        <th>
                            รวมมูลค่า
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in creditNoteList.OrderByDescending(x => x.CreateDate))
                {
                    var totalPrice = item.AccountCreditNoteDetails.Sum(x => x.UnitPrice * x.Quantity).ToString("N2");
                        <tr>
                            <td>
                                @item.CreditNoteCode
                            </td>
                            <td>
                                @if (item.IsPrinted == true)
                                {
                                    <p style="color:green;">พิมพ์เอกสารออกจากระบบแล้ว</p>
                                }
                                else
                                {
                                    <p style="color:red;">รอพิมพ์เอกสารออกจากระบบ</p>
                                }
                            </td>
                            <td>
                                <input type="checkbox" checked="@item.IsPayForCash" />
                            </td>
                            <td>
                                @item.Description
                            </td>
                            <td>
                                @item.CreateDate.ToShortDateString()
                            </td>
                            <td>
                                @item.CreateBy
                            </td>
                            <td>
                                @totalPrice
                            </td>
                            <td>
                                <a style="padding:5px;" class="btn btn-info btn-sm" title="Detail" href="@Url.Action("Detail", "CreditNoteDetail", new { creditNoteCode = item.CreditNoteCode, accountInvoiceNo = accountInvoice.InvoiceNo })">Detail</a>
                                @if (item.IsPrinted == false)
                                {
                                    <a style="padding:5px;" class="btn btn-danger btn-sm" title="Delete" href="@Url.Action("Delete", "CreditNote", new { creditNoteCode = item.CreditNoteCode })">Delete</a>
                                }
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
}

<!-- Modal 1 Create credit note document. -->
@using (Html.BeginForm("Create", "CreditNote", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.AccountInvoiceNo)
    <div class="modal fade" id="createModal" tabindex="-1" role="dialog" aria-labelledby="createModal" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">บันทึกใบลดหนี้</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-12">
                            <figure>
                                <blockquote class="blockquote">
                                    <p>คำเตือนก่อนการบันทึกข้อมูล!</p>
                                </blockquote>
                                <figcaption class="blockquote-footer">
                                    โปรดตรวจสอบวันที่ที่ท่านระบุให้ถูกต้อง เนื่องจากวันที่ที่ท่านระบุจะถูกนำไปใช้ในการสร้างรหัสให้กับใบลดหนี้ ระบบไม่สามารถแก้ไขข้อมูลรหัสใบลดหนี้ได้
                                </figcaption>
                            </figure>
                        </div>
                    </div>
                    <div class="row" style="margin-top:20px;">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <div class="form-check">
                                    @Html.CheckBoxFor(model => model.IsPayForCash, new { @class = "form-check-input" }) ชำระเป็นเงินสด
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="createDate" class="control-label">วันที่ออกใบลดหนี้</label>
                                <div>
                                    <input type="date" name="createDate" id="CreateDate" class="form-control" value="@DateTime.Today.ToString("yyyy-MM-dd")" />
                                    @Html.ValidationMessageFor(model => model.CreateDate)
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="createDate" class="control-label">หมายเหตุ / รายละเอียด</label>
                                <div>
                                    @Html.DropDownListFor(model => model.Description,
                                   new List<SelectListItem>
                                   {
                                       new SelectListItem { Text ="รับคืนชุดป้องกันสารเคมี", Value = "รับคืนชุดป้องกันสารเคมี"},
                                       new SelectListItem { Text ="รับคืนปัจจัยการผลิต", Value = "รับคืนปัจจัยการผลิต"}
                                   }, new { @class = "form-control", @type = "text" })
                                    @Html.ValidationMessageFor(model => model.Description)
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">ปิด</button>
                    <button type="submit" class="btn btn-danger" id="confirmSubmitButton">สร้างใบลดหนี้</button>
                </div>
            </div>
        </div>
    </div>
}