BUWebApp/Areas/Supervisor/Controllers/CY202201SearchFarmerController.cs
using BusinessLayer;
using BUWebApp.Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BUWebApp.Areas.Supervisor.Controllers
{
    [Authorize(Roles = "Supervisor")]
    public class CY202201SearchFarmerController : Controller
    {
        // GET: Supervisor/CY202201SearFarmer
        [HttpGet]
        public ActionResult Index(string supplierCode)
        {
            AppSetting.Username = HttpContext.User.Identity.Name;
            var _supervisor = AppSetting.SupervisorUser;
            var _crop = AppSetting.Crop;

            List<SelectListItem> supplierList = new List<SelectListItem>();
            foreach (var item in BuyingFacade.SupplierBL().GetByArea(_supervisor.AreaCode))
            {
                supplierList.Add(new SelectListItem
                {
                    Text = item.SupplierCode,
                    Value = item.SupplierCode
                });
            }
            ViewBag.SupplierList = supplierList;
            ViewBag.SupplierCode = supplierCode;

            return View(BuyingFacade.RegistrationBL()
                .GetBySupplier(_crop.Crop1, supplierCode));
        }
    }
}

BUWebApp/Areas/Supervisor/Views/CY202201SearchFarmer/Index.cshtml
@model IEnumerable<DomainModel.RegistrationFarmer>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Supervisor/Views/Shared/_Layout.cshtml";
}

<script type="text/javascript">
    $(document).ready(function (e) {
        $("#detailsTable").DataTable({
            "order": [[0, "asc"]]
        });
    })
</script>

<h3>Search Farmer For Return CPA container and Basket</h3>
<h6>ค้นหาข้อมูลชาวไร่เพื่อคืนขยะสารเคมีและตะกร้าเพื่อลดหนี้ค่าตะกร้า</h6>
<hr />
<div class="row">
    <div class="col-sm-12">
        <form class="form-inline justify-content-center">
            <div class="form-group mx-sm-3 mb-2">
                @Html.DropDownList("supplierCode", (IEnumerable<SelectListItem>)ViewBag.SupplierList, new { @class = "form-control form-control-sm" })
                <button class="btn btn-primary btn-sm ml-1" formmethod="get" formaction="@Url.Action("Index","CY202201SearchFarmer",new {supplierCode = ViewBag.SupplierCode })"><i class="fas fa-search"></i> แสดงข้อมูล</button>
                <a class="btn btn-secondary btn-sm ml-1" href="@Url.Action("Index","Home")"><i class="fas fa-arrow-circle-left"></i> Back To Home</a>
            </div>
        </form>
    </div>
</div>

<table id="detailsTable" class="table table-responsive-sm">
    <thead class="table-dark">
        <tr>
            <th>Farmer Code</th>
            <th>Prefix</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Citizen ID</th>
            <th>Sign Contract Rai</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @{
            var totalRecord = 0;
        }
        @foreach (var item in Model.OrderBy(x => x.FarmerCode))
        {
            <tr>
                <td>
                    @item.FarmerCode
                </td>
                <td>
                    @item.Farmer.Person.Prefix
                </td>
                <td>
                    @item.Farmer.Person.FirstName
                </td>
                <td>
                    @item.Farmer.Person.LastName
                </td>
                <td>
                    @item.Farmer.Person.CitizenID
                </td>
                <td>
                    @item.QuotaFromSignContract
                </td>
                <td style="width:150px;">
                    <a title="Create return no." class="btn btn-outline-success btn-sm" href='@Url.Action("Index", "CY202201Return", new {crop = item.Crop, farmerCode = item.FarmerCode })'>
                        ดูรายละเอียด
                    </a>
                </td>
            </tr>
            totalRecord++;
        }
    </tbody>
</table>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}