BUWebApp/Areas/Admin/Controllers/ReturnItemController.cs
using AGMInventorySystemEntities;
using BusinessLayer;
using BusinessLayer.Model;
using BUWebApp.Areas.Admin.Models;
using DomainModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BUWebApp.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ReturnItemController : Controller
    {
        // GET: Admin/ReturnItem
        public ActionResult Index()
        {
            ViewBag.Items = new List<material_item>();
            ViewBag.Brands = new List<material_brand>();

            ViewBag.Categories = AGMInventorySystemBL.BLServices
                .material_categoryBL()
                .GetAll()
                .OrderBy(x => x.category_name)
                .Select(x => new material_category
                {
                    categoryid = x.categoryid,
                    category_name = x.category_name
                })
                .ToList();

            ViewBag.ItemTypes = BuyingFacade.CY202201ReturnItemBL().GetItemType();

            var returnItemList = BuyingFacade.CY202201ReturnItemBL().GetAll();
            var agmInventoryItemList = AGMInventorySystemBL.BLServices.material_itemBL().GetAll();

            ViewBag.ReturnItemList = (from a in returnItemList
                                      from b in agmInventoryItemList
                                      where a.ReturnItemID == b.itemid
                                      select new m_CY202201ReturnItem
                                      {
                                          ReturnItemID = a.ReturnItemID,
                                          ItemName = b.item_name,
                                          ItemType = a.ItemType,
                                          IsActive = a.IsActive,
                                          Remark = a.Remark
                                      })
                               .OrderBy(x => x.ItemType)
                               .ThenBy(x => x.ItemName)
                               .ToList();

            return View(new vm_ReturnItem
            {
                ItemType = "ตะกร้า",
                IsActive = true
            });
        }

        [HttpPost]
        public ActionResult Add(vm_ReturnItem collection)
        {
            BuyingFacade.CY202201ReturnItemBL()
                .Add(new CY202201ReturnItem
                {
                    ReturnItemID = collection.ItemID,
                    ItemType = collection.ItemType,
                    IsActive = collection.IsActive,
                    Remark = collection.Remark,
                    RecordUser = HttpContext.User.Identity.Name,
                    RecordDate = DateTime.Now,
                    ModifiedUser = HttpContext.User.Identity.Name,
                    ModifiedDate = DateTime.Now
                });
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int itemID)
        {
            var item = BuyingFacade.CY202201ReturnItemBL().GetSingle(itemID);
            if (item == null)
                throw new ArgumentException("ไม่พบข้อมูล ReturnItem นี้ในระบบ");

            var agmInventoryItem = AGMInventorySystemBL.BLServices.material_itemBL().GetSingle(itemID);
            if (agmInventoryItem == null)
                throw new ArgumentException("ไม่พบข้อมูล ReturnItem นี้ในระบบ AGM Inventory โปรดติดต่อแผนกไอทีเพื่อตรวจสอบ");

            ViewBag.ItemTypes = BuyingFacade.CY202201ReturnItemBL().GetItemType();

            return View(new m_CY202201ReturnItem
            {
                ReturnItemID = item.ReturnItemID,
                ItemType = item.ItemType,
                IsActive = item.IsActive,
                Remark = item.Remark,
                RecordDate = item.RecordDate,
                RecordUser = item.RecordUser,
                ModifiedDate = item.ModifiedDate,
                ModifiedUser = item.ModifiedUser,
                ItemName = agmInventoryItem.item_name
            });
        }

        [HttpPost]
        public ActionResult Edit(m_CY202201ReturnItem collection)
        {
            BuyingFacade.CY202201ReturnItemBL()
                .Update(new CY202201ReturnItem
                {
                    ReturnItemID = collection.ReturnItemID,
                    ItemType = collection.ItemType,
                    IsActive = collection.IsActive,
                    Remark = collection.Remark,
                    ModifiedDate = DateTime.Now,
                    ModifiedUser = HttpContext.User.Identity.Name
                });
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Delete(int itemID)
        {
            BuyingFacade.CY202201ReturnItemBL().Delete(itemID);
            return RedirectToAction("Index");
        }
    }
}

BUWebApp/Controllers/AGMInventoriesController.cs
using BusinessLayer;
using BusinessLayer.Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BUWebApp.Controllers
{
    public class AGMInventoriesController : Controller
    {
        [HttpGet]
        public JsonResult Items(int categoryid, int brandid)
        {
            try
            {
                List<SelectListItem> list = new List<SelectListItem>();
                list = AGMInventorySystemBL.BLServices.material_itemBL()
                    .GetByCategory(categoryid)
                    .Where(x => x.brandid == brandid)
                    .OrderBy(x => x.item_name)
                    .Select(x => new SelectListItem
                    {
                        Text = x.item_name,
                        Value = x.itemid.ToString()
                    }).ToList();

                return Json(new SelectList(list, "Value", "Text"), JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpGet]
        public JsonResult ItemsByCategory(int categoryid)
        {
            try
            {
                List<SelectListItem> list = new List<SelectListItem>();
                list = AGMInventorySystemBL.BLServices.material_itemBL()
                    .GetByCategory(categoryid)
                    .OrderBy(x => x.item_name)
                    .Select(x => new SelectListItem
                    {
                        Text = x.item_name + " (" + x.material_unit.unit_name + ")",
                        Value = x.itemid.ToString()
                    }).ToList();

                return Json(new SelectList(list, "Value", "Text"), JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpGet]
        public JsonResult Brands(int categoryid)
        {
            try
            {
                List<SelectListItem> list = new List<SelectListItem>();
                list = AGMInventorySystemBL.BLServices
                    .material_brandBL()
                    .GetAll()
                    .Where(x => x.categoryid == categoryid)
                    .OrderBy(x => x.brand_name)
                    .Select(x => new SelectListItem
                    {
                        Text = x.brand_name,
                        Value = x.brandid.ToString()
                    }).ToList();

                return Json(new SelectList(list, "Value", "Text"), JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpGet]
        public JsonResult Categories()
        {
            try
            {
                List<SelectListItem> list = new List<SelectListItem>();
                list = AGMInventorySystemBL.BLServices.material_categoryBL()
                    .GetAll()
                    .OrderBy(x => x.category_name)
                    .Select(x => new SelectListItem
                    {
                        Text = x.category_name,
                        Value = x.categoryid.ToString()
                    }).ToList();
                return Json(new SelectList(list, "Value", "Text"), JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpGet]
        public JsonResult CategoriesFromItemCondition(short crop, string supplierCode)
        {
            try
            {
                List<SelectListItem> list = new List<SelectListItem>();
                list = BusinessLayer.Helper.CropInputsItemHelper
                    .GetBySupplierCode(crop, supplierCode)
                    .GroupBy(x => new { x.Category })
                    .OrderBy(x => x.Key.Category)
                    .Select(x => new SelectListItem
                    {
                        Text = x.Key.Category,
                        Value = x.Key.Category.ToString()
                    }).ToList();
                return Json(new SelectList(list, "Value", "Text"), JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpGet]
        public JsonResult ItemsFromItemCondition(string category, string supplierCode, string filter)
        {
            try
            {
                List<SelectListItem> resultList = new List<SelectListItem>();

                var list = BusinessLayer.Helper.CropInputsItemHelper
                    .GetBySupplierCode(BuyingFacade.CropBL().GetDefault().Crop1, supplierCode)
                    .Where(x => x.Category == category && x.IsNotToInvoice == false)
                    .ToList();

                if (filter != "all")
                    resultList = list.Where(x => x.IsVat == (filter == "IncludeVAT" ? true : false))
                    .OrderBy(x => x.ItemName)
                    .Select(x => new SelectListItem
                    {
                        Text = x.ItemName + " (" + x.Brand + ")",
                        Value = x.ConditionID.ToString()
                    }).ToList();
                else
                    resultList = list
                    .OrderBy(x => x.ItemName)
                    .Select(x => new SelectListItem
                    {
                        Text = x.ItemName + " (" + x.Brand + ")",
                        Value = x.ConditionID.ToString()
                    }).ToList();

                return Json(new SelectList(resultList, "Value", "Text"), JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpGet]
        public JsonResult ItemsWithCondition(string category, string supplierCode)
        {
            try
            {
                var crop = Helper.AppSetting.Crop.Crop1;
                var list = CropInputsItemHelper
                    .GetBySupplierCode(crop, supplierCode)
                    .Where(x => x.Category == category && x.IsNotToInvoice == false)
                    .OrderBy(x => x.ItemName)
                    .ToList();

                return Json(list, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpGet]
        public JsonResult NotToInvoiceItemsFromItemCondition(string category, string supplierCode)
        {
            try
            {
                List<SelectListItem> resultList = new List<SelectListItem>();
                resultList = BusinessLayer.Helper.CropInputsItemHelper
                    .GetBySupplierCode(BuyingFacade.CropBL().GetDefault().Crop1, supplierCode)
                    .Where(x => x.Category == category && x.IsNotToInvoice == true)
                    .OrderBy(x => x.ItemName)
                    .Select(x => new SelectListItem
                    {
                        Text = x.ItemName + " (" + x.Brand + ")",
                        Value = x.ConditionID.ToString()
                    }).ToList();

                return Json(new SelectList(resultList, "Value", "Text"), JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpGet]
        public JsonResult ItemSingleFromItemCondition(Guid conditionID)
        {
            try
            {
                return Json(BusinessLayer.Helper.CropInputsItemHelper.GetSingle(conditionID), JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpGet]
        public JsonResult Package(short crop, string supplierCode)
        {
            try
            {
                List<SelectListItem> list = new List<SelectListItem>();
                list = BuyingFacade.CropInputsPackageBL()
                    .GetBySupplier(crop, supplierCode)
                    .OrderBy(x => x.PackageCode)
                    .Select(x => new SelectListItem
                    {
                        Text = x.PackageCode + " (" + x.Description + ")",
                        Value = x.PackageCode
                    }).ToList();

                return Json(new SelectList(list, "Value", "Text"), JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpGet]
        public JsonResult PackageDetails(string packageCode)
        {
            try
            {
                var list1 = BusinessLayer.Helper.CropInputsItemHelper
                     .GetByPackage(packageCode)
                     .OrderBy(x => x.Category)
                     .ThenBy(x => x.ItemName)
                     .ThenBy(x => x.Brand)
                     .ToList();

                return Json(list1, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
    }
}

BUWebApp/Areas/Admin/Views/ReturnItem/Edit.cshtml
@model BusinessLayer.Model.m_CY202201ReturnItem

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


<h3>Edit CPA Container & Basket</h3>
<h6>แก้ไขข้อมูลรายการตัวเลือกขยะสารเคมีและตะกร้า</h6>
<hr />
@using (Html.BeginForm("Edit", "ReturnItem", FormMethod.Post, new { @class = "row g-3" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ReturnItemID)
    <div class="col-12 mt-3">
        <label class="control-label">Item Name :</label>
        @Html.EditorFor(model => model.ItemName, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly", @placeholder = "Item Name" } })
        @Html.ValidationMessageFor(model => model.ItemName, "", new { @class = "text-danger" })
    </div>
    <div class="col-12 mt-3">
        <label class="control-label">Item Type :</label>
        @Html.DropDownListFor(model => model.ItemType, new SelectList(@ViewBag.ItemTypes, "ItemType", "ItemType"), "โปรดเลือกรายการ", new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.ItemType, "", new { @class = "text-danger" })
    </div>
    <div class="col-12 mt-3">
        <label class="control-label">Remark :</label>
        @Html.EditorFor(model => model.Remark, new { htmlAttributes = new { @class = "form-control", @placeholder = "Remark" } })
        @Html.ValidationMessageFor(model => model.Remark, "", new { @class = "text-danger" })
    </div>
    <div class="col-12 mt-3">
        @Html.CheckBoxFor(model => model.IsActive, new { @class = "form-check-input" })
        <label for="IsActive" class="form-check-label">Is Active (ให้แสดงบนหน้าบันทึกข้อมูลการคืนขยะสารเคมีและตะกร้า)</label>
        @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
    </div>
    <div class="col-12 mt-3">
        <button class="btn btn-primary" type="submit" id="addItem" name="addItem"><i class="fas fa-save"></i> บันทึกข้อมูล</button>
        <a class="btn btn-secondary" href="@Url.Action("Index","ReturnItem",null,null)"><i class="fas fa-arrow-circle-left"></i>  ย้อนกลับ</a>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BUWebApp/Areas/Admin/Views/ReturnItem/Index.cshtml
@model BUWebApp.Areas.Admin.Models.vm_ReturnItem

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<script type="text/javascript">
    $(document).ready(function (e) {
        $("#confirmSubmitButton").click(function () {
            if (fromValidation() == false) {
                event.preventDefault();
            }
        });

        $("#detailsTable").DataTable({
            "order": [[0, "asc"]]
        });

        $("#Category").change(function () {
            bindingBrands();
            bindingItems();
        });

        $("#Brand").change(function () {
            bindingItems();
        });

        function bindingBrands() {
            var categoryid = $("#Category").val();
            var brandid = $("#Brand").val();
            var resourceUrl = '@Url.Action("Brands", "AGMInventories", new { Area = "" })?categoryid=' + categoryid;
            $("#Brand").empty("โปรดเลือก brand");
            $.ajax({
                type: 'GET',
                dataType: "json",
                url: resourceUrl,
                data: null,
                success: function (info) {
                    $("#Brand").append('<option value="">โปรดเลือกรายการ</option>');
                    $.each(info, function (i, info) {
                        $("#Brand").append('<option value="' + info.Value + '">' +
                             info.Text + '</option>');
                    });
                }
            });
        }

        function bindingItems() {
            var categoryid = $("#Category").val();
            var brandid = $("#Brand").val();
            var resourceUrl = '@Url.Action("Items", "AGMInventories", new { Area = "" })?categoryid=' + categoryid + '&brandid=' + brandid;
            $("#ItemID").empty("โปรดเลือกประเภท");
            $.ajax({
                type: 'GET',
                dataType: "json",
                url: resourceUrl,
                data: null,
                success: function (info) {
                    $("#ItemID").append('<option value="">โปรดเลือกรายการ</option>');
                    $.each(info, function (i, info) {
                        $("#ItemID").append('<option value="' + info.Value + '">' +
                             info.Text + '</option>');
                    });
                }
            });
        }

        function fromValidation() {
            //if ($("#CreateDate").val() == null || $("#CreateDate").val() == "") {
            //    alert("โปรดระบุวันที่สร้างเอกสารใบลดหนี้");
            //    $("#CreateDate").focus();
            //    return false;
            //}

            //if ($("#Description").val() == null || $("#Description").val() == "") {
            //    alert("โปรดระบุหมายเหตุของการทำใบลดหนี้");
            //    $("#Description").focus();
            //    return false;
            //}

            //if ($("#IsPayForCash").is(":checked") == true) {
            //    var result = confirm("ท่านต้องการออกใบลดหนี้แบบชำระเป็นเงินสดใช่หรือไม่?");
            //    if (result == false)
            //        return false;
            //}

            return true;
        }
    });
</script>

<h3>CPA Container & Basket</h3>
<h6>บันทึกข้อมูลรายการตัวเลือกขยะสารเคมีและตะกร้า</h6>
<hr />
<div class="row g-3">
    <div class="col-sm-12">
        <button class="btn btn-success btn-sm" data-bs-toggle="modal" data-bs-target="#addModal"><i class="fas fa-plus"></i> Add Item</button>
        <a class="btn btn-secondary btn-sm ml-1" href="@Url.Action("Index","Home")"><i class="fas fa-arrow-circle-left"></i> Back</a>
    </div>
</div>

<div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="addModal" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">บันทึกข้อมูล</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("Add", "ReturnItem", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    <div class="col-12 mt-3">
                        <label class="form-label">Category :</label>
                        @Html.DropDownList("Category", new SelectList(@ViewBag.Categories, "categoryid", "category_name"), "โปรดเลือกประเภท", new { @class = "form-control col-sm-12" })
                    </div>
                    <div class="col-12 mt-3">
                        <label class="form-label">Brand :</label>
                        @Html.DropDownListFor(model => model.Brand, new SelectList(@ViewBag.Brands, "brandid", "brand_name"), "โปรดเลือกรายการ", new { @class = "form-control col-sm-12" })
                    </div>
                    <div class="col-12 mt-3">
                        <label class="form-label">Item :</label>
                        @Html.DropDownListFor(model => model.ItemID, new SelectList(@ViewBag.Items, "itemid", "item_name"), "โปรดเลือกรายการ", new { @class = "form-control col-sm-12" })
                        @Html.ValidationMessageFor(model => model.ItemID, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-12 mt-3">
                        <label class="form-label">Item Type :</label>
                        @Html.DropDownListFor(model => model.ItemType, new SelectList(@ViewBag.ItemTypes, "ItemType", "ItemType"), "โปรดเลือกรายการ", new { @class = "form-control col-sm-12" })
                        @Html.ValidationMessageFor(model => model.ItemType, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-12 mt-3">
                        <label class="control-label">Remark :</label>
                        @Html.EditorFor(model => model.Remark, new { htmlAttributes = new { @class = "form-control col-sm-12", @placeholder = "Remark" } })
                        @Html.ValidationMessageFor(model => model.Remark, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-check mt-3">
                        @Html.CheckBoxFor(model => model.IsActive, new { @class = "form-check-input" })
                        <label class="form-check-label" for="IsActive">Is Active (ให้แสดงบนหน้าบันทึกข้อมูล)</label>
                    </div>
                    <div class="modal-footer mt-3">
                        <button type="submit" class="btn btn-primary" id="confirmSubmitButton"><i class="fas fa-plus"></i>บันทึกข้อมูล</button>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

<div class="table-responsive mt-3">
    <table id="detailsTable" class="table table-striped table-hover table-sm">
        <thead class="table-dark">
            <tr>
                <th>Item Name</th>
                <th>Item Type</th>
                <th>Is Active</th>
                <th>Remark</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @{
                var totalRecord = 0;
            }
            @foreach (var item in (List<BusinessLayer.Model.m_CY202201ReturnItem>)ViewBag.ReturnItemList)
            {
                <tr>
                    <td>
                        @item.ItemName
                    </td>
                    <td>
                        @item.ItemType
                    </td>
                    <td style="text-align:center;">
                        @if (item.IsActive == true)
                        {
                            <i class="fa fa-check-circle" style="color:green;"></i>
                        }
                    </td>
                    <td>
                        @item.Remark
                    </td>
                    <td style="width:150px;">
                        <a title="edit" class="btn btn-success btn-sm" href='@Url.Action("Edit", "ReturnItem", new { itemID = item.ReturnItemID })'>
                            Edit
                        </a>
                        <a title="delete" class="btn btn-danger btn-sm" href='@Url.Action("Delete", "ReturnItem", new { itemID = item.ReturnItemID })'>
                            Delete
                        </a>
                    </td>
                </tr>
                totalRecord++;
            }
        </tbody>
    </table>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}