BUWebApp/Areas/ExtensionAgent/Controllers/MachineAndFarmEqipmentController.cs
using BusinessLayer;
using BUWebApp.Helper;
using DomainModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace BUWebApp.Areas.ExtensionAgent.Controllers
{
    [Authorize(Roles = "ExtensionAgent")]
    public class MachineAndFarmEqipmentController : Controller
    {
        [HttpGet]
        public ActionResult Index(string id)
        {
            AppSetting.Username = HttpContext.User.Identity.Name;
            var _supplierUser = AppSetting.SupplierUser;
            var _crop = AppSetting.Crop;
            ViewBag.SupplierCode = _supplierUser.SupplierCode;

            var farmer = BuyingFacade.FarmerBL()
                    .GetByCitizenID(id)
                    .Single(f => f.Supplier == _supplierUser.SupplierCode);
            if (farmer == null)
                throw new ArgumentNullException("ไม่พบข้อมูลการลงทะเบียนเป็นสมาชิกกับตัวแทน " +
                    _supplierUser.SupplierCode + " ในระบบ");

            ViewBag.MachineFarmAndEqipments = BuyingFacade.MachineAndFarmEquipmentBL()
                .GetAll()
                .Where(x => x.IsActive == true)
                .OrderBy(x => x.MachineAndFarmEquipmentName);

            var list = BuyingFacade.FarmerMachineAndFarmEquipmentBL().GetByCitizenID(_crop.Crop1, id);
            return View(new Models.vm_FarmEquipment
            {
                CitizenID = farmer.CitizenID,
                Crop = _crop.Crop1,
                FarmEquipmentList = list,
                Farmer = farmer
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Models.vm_FarmEquipment collection)
        {
            AppSetting.Username = HttpContext.User.Identity.Name;
            var _supplierUser = AppSetting.SupplierUser;
            var _crop = AppSetting.Crop;

            ViewBag.SupplierCode = _supplierUser.SupplierCode;
            ViewBag.MachineFarmAndEqipments = BuyingFacade.MachineAndFarmEquipmentBL()
                .GetAll()
                .OrderBy(x => x.MachineAndFarmEquipmentName);

            if (!ModelState.IsValid)
            {
                collection.FarmEquipmentList = BuyingFacade.FarmerMachineAndFarmEquipmentBL()
                    .GetByCitizenID(_crop.Crop1, collection.CitizenID);
                return View("Index", collection);
            }

            BuyingFacade.FarmerMachineAndFarmEquipmentBL().Add(
                new FarmerMachineAndFarmEquipment
                {
                    CitizenID = collection.CitizenID,
                    Crop = _crop.Crop1,
                    MachineAndFarmEquipmentID = collection.MachineAndFarmEquipmentID,
                    LifeTime = collection.LifeTime,
                    Quantity = collection.Quantity,
                    CanUse = collection.CanUse,
                    ModifiedDate = DateTime.Now,
                    ModifiedUser = AppSetting.Username
                });

            return RedirectToAction("Index", new { id = collection.CitizenID });
        }

        [HttpGet]
        public ActionResult Delete(short crop, string citizenID, Guid machineID)
        {
            BuyingFacade.FarmerMachineAndFarmEquipmentBL().Delete(crop, citizenID, machineID);
            return RedirectToAction("Index", new { id = citizenID });

        }
    }
}

BUWebApp/Areas/ExtensionAgent/Views/MachineAndFarmEqipment/Index.cshtml
@model BUWebApp.Areas.ExtensionAgent.Models.vm_FarmEquipment
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/ExtensionAgent/Views/Shared/_Layout.cshtml";
}
<script>
    $(document).ready(function () {
        $("#submitButton").click(function () {
            if (formValidation() == false) {
                event.preventDefault();
            }
        });
    });

    function formValidation() {
        if ($("#MachineAndFarmEquipmentID").val() == "") {
            alert("โปรดเลือกชนิดเครื่องจักรและอุปกรณ์");
            $("#MachineAndFarmEquipmentID").focus();
            return false;
        }
        if ($("#Quantity").val() == "") {
            alert("โปรดระบุจำนวน");
            $("#Quantity").focus();
            return false;
        }
        if ($("#Quantity").val() < 1) {
            alert("จำนวนจะต้องมากกว่า 0");
            $("#Quantity").focus();
            return false;
        }
        if ($("#LifeTime").val() == "") {
            alert("โปรดระบุอายุการใช้งาาน");
            $("#LifeTime").focus();
            return false;
        }
        if ($("#LifeTime").val() < 0) {
            alert("อายุการใช้งานต้องไม่ต่ำกว่า 0");
            $("#LifeTime").focus();
            return false;
        }
        return true;
    }
</script>

<h4>ข้อมูลเครื่องทุ่นแรงและอุปกรณ์ทางการเกษตร / Manage Farm Machine & Eqipment</h4>
<hr />

@using (Html.BeginForm("Create", "MachineAndFarmEqipment"))
{
    @Html.AntiForgeryToken()
    <div class="row">
        <div class="col-12">
            <input name="CitizenID" type="hidden" value="@Model.CitizenID" />
            <div class="card">
                <div class="card-header">
                    @Model.Farmer.FarmerCode @Model.Farmer.Person.Prefix@Model.Farmer.Person.FirstName   @Model.Farmer.Person.LastName
                </div>
                <div class="card-body">
                    <div class="form">
                        @Html.ValidationSummary(true)
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    @Html.Label("ชนิดเครื่องจักรและอุปกรณ์:")<span style="color:red;">*</span>
                                    @Html.DropDownList("MachineAndFarmEquipmentID", new SelectList(@ViewBag.MachineFarmAndEqipments, "MachineAndFarmEquipmentID", "MachineAndFarmEquipmentName"), new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.MachineAndFarmEquipmentID)
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="form-group">
                                    @Html.Label("จำนวน:")<span style="color:red;">*</span>
                                    @Html.TextBoxFor(model => model.Quantity, new { @class = "form-control", type = "number", @placeholder = "Quantity" })
                                    @Html.ValidationMessageFor(model => model.Quantity)
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="form-group">
                                    @Html.Label("ใช้มาแล้วกี่ปี:")<span style="color:red;">*</span>
                                    @Html.TextBoxFor(model => model.LifeTime, new { @class = "form-control", type = "number", @placeholder = "Life time", @min = "0" })
                                    @Html.ValidationMessageFor(model => model.LifeTime)
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-3">
                                <div class="form-group">
                                    <input type="checkbox" value="true" name="CanUse"> สามารถใช้การได้:
                                    @Html.ValidationMessageFor(model => model.CanUse, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary" id="submitButton" name="submitButton"><i class="fa fa-floppy-o"></i> Save</button>
                        <button type="reset" class="btn btn-secondary"><i class="fa fa-refresh"></i> Reset</button>
                        <a class="btn btn-outline-secondary" href="@Url.Action("Index","PreRegistrationForm", new { id = @Model.Farmer.Person.CitizenID })">Back</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
}
<div class="row">
    <div class="col-md-12" style="margin-top:20px;">
        <table class="table table-hover table-striped">
            <tr class="table-info">
                <th>รายการอุปกรณ์และเครื่องมือทางการเกษตร</th>
                <th>จำนวน</th>
                <th>อายุการใช้งาน</th>
                <th>ใช้งานได้</th>
                <th></th>
            </tr>
            @foreach (var item in Model.FarmEquipmentList)
            {
                <tr>
                    <td>@item.MachineAndFarmEquipment.MachineAndFarmEquipmentName</td>
                    <td>@item.Quantity</td>
                    <td>@item.LifeTime</td>
                    <td><input type="checkbox" checked="@item.CanUse" name="CanUse"></td>
                    <td>
                        <a class="btn btn-danger btn-sm" title="Delete" href="@Url.Action("Delete", new {crop =item.Crop, citizenID = item.CitizenID, machineID = item.MachineAndFarmEquipmentID})"><i class="fa fa-remove"></i> Delete</a>
                    </td>
                </tr>
            }
        </table>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}